version: "3.1"
services:
  es:
    container_name: es
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
