version: "3.8"

services:
  elasticsearch:
    container_name: es
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - ./elasticsearch/data:/usr/share/elasticsearch/data
